import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import FloatingMenu from '../components/FloatingMenu';
import Navbar from '../components/Navbar';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Res",
  description: "Generated by create mmk",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning
  className={`${geistSans.variable} ${geistMono.variable}`}
>
      <body>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
           <Navbar/>
          <main className="pt-16 max-w-6xl mx-auto px-4">
          {children}
          </main>
    
          <FloatingMenu />
        </ThemeProvider>
      </body>
    </html>
  );
}
