import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import FloatingMenu from '../components/FloatingMenu';
import Navbar from '../components/Navbar';
import { Toaster } from "sonner"

export const metadata: Metadata = {
  title: "Res",
  description: "Generated by create mmk",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
           <Navbar/>
          <main className="pt-16 max-w-6xl mx-auto px-4">
          {children}
          </main>
    
          <FloatingMenu />
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
